version: '3.7'

services:
  mysql:
    build:
      args:
        VERSION: $MYSQL_VERSION
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
      args:
        VERSION: $NGINX_VERSION
    depends_on:
      - php-fpm
    ports:
      - 8000:80
    volumes:
      - ./assets:/app/public
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
      args:
        VERSION: $PHP_VERSION
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php-fpm'
    depends_on:
      - mysql
    volumes:
      - .:/app
